language: php
sudo: required
dist: trusty

php:
  - "7.2"

cache:
  directories:
    - $HOME/.composer/cache

addons:
  chrome: stable

install:
  - cp .env.travis .env
  - mysql -e 'create database todoapp_test;'
  - composer self-update
  - composer install --no-interaction
  - php artisan key:generate
  - php artisan migrate

before_script:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
  - php artisan serve &

script:
  - vendor/bin/phpunit
  - php artisan dusk